---
- hosts: all
  tasks:
  - name: Group all hosts by os
    group_by: key={{ ansible_os_family }}
  tags:
  - always

- name: Bootstrap
  hosts: all
  roles:
  - bootstrap
  tags:
  - bootstrap
  become: true

- name: Install and configure git
  hosts: all
  roles:
  - git
  tags:
  - git
  become: true

- name: Configure shell
  hosts: all
  roles:
  - zsh
  tags:
  - shell

#- name: Configure terminal
#  hosts: all
#  roles:
#  - term
#  tags:
#  - term

- name: Install and configure vim
  hosts: all
  roles:
  - vim
  tags:
  - vim

- name: Install docker
  hosts: all
  roles:
    - docker
  tags:
    - docker

- name: Install dropbox
  hosts: all
  roles:
  - dropbox
  tags:
  - dropbox
  become: true

- name: Install and configure oh-my-zsh
  hosts: all
  roles:
    - zsh
  tags:
    - zsh

- name: Install slack
  hosts: all
  roles:
    - slack
  tags:
    - slack

- name: Prepare for music
  hosts: all
  roles:
    - audio
  tags:
    - audio

- name: Prepare to read
  hosts: all
  roles:
    - read
  tags:
    - read
  become: true

- name: Install misc packages
  hosts: all
  roles:
    - misc
  tags:
    - misc
