---
- name: Install zsh
  package:
    name: zsh
    state: latest
  become: true

- name: Clone oh-my-zsh
  git:
    repo: "{{ omz_repo }}"
    dest: "~/.oh-my-zsh" 

- name: Copy example zshrc
  shell: "cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc"

- name: Set zsh theme
  lineinfile:
    dest: "~/.zshrc"
    regexp: '^ZSH_THEME='
    line: "ZSH_THEME={{ zsh_theme }}"

- name: Set DEFAULT_USER
  lineinfile:
    dest: "~/.zshrc"
    line: "DEFAULT_USER=$USER"

- name: Add time to prompt
  lineinfile:
    dest: "~/.zshrc"
    line: 'prompt_context () {prompt_segment black default "%t"}'

- name: Change shell to zsh
  shell: chsh -s /bin/zsh
  become: true

- name: Install powerline
  shell: pip install powerline-status
  become: true

- name: reload zshrc
  shell: "source ~/.zshrc"
  args:
    executable: /usr/bin/zsh

- name: reload shell
  shell: exec $SHELL
