---
- name: Add alias to aws-cli docker container
  lineinfile:
    dest: "~/.zshrc"
    line: |
      alias aws='docker run --rm -t $(tty &>/dev/null && echo "-i") -e "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" -e "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" -e "AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}" -v "$(pwd):/project" {{ aws_cli_container }}'

- name: reload zshrc
  shell: "source ~/.zshrc"
  args:
    executable: /usr/bin/zsh
  when: ansible_system == "Linux"

- name: reload zshrc
  shell: "source ~/.zshrc"
  args:
    executable: /usr/local/bin/zsh
  when: ansible_system == "Darwin"
