---
- block:
  - name: Install docker prereqs
    package:
      name: "{{ item }}"
      state: latest
    with_items:
      - apt-transport-https
      - ca-certificates
      - software-properties-common

  - name: enable docker debian apt repository
    lineinfile:
      dest: /etc/apt/sources.list
      line: "{{ docker_source }}"

  - name: Add docker official GPG key
    apt_key:
      url: "{{ docker_gpg_source }}"
      id: "{{ docker_gpg_key_id }}"
      state: present

  - name: apt-get update
    apt:
      update_cache: yes
  become: true

- include: docker-engine.yml

- include: docker-compose.yml
