---
- block:
  - name: Install HTTPS support for apt
    package:
      name: apt-transport-https
      state: latest

  - name: Install CA certs
    package:
      name: ca-certificates
      state: latest

  - name: Install software properties common
    package:
      name: software-properties-common
      state: latest

  - name: enable docker debian apt repository
    lineinfile:
      dest: /etc/apt/sources.list
      line: "{{ docker_source }}"

  - name: Add docker official GPG key
    apt_key:
      url: "{{ docker_gpg_source }}"
      id: "{{ docker_gpg_key_id }}"
      state: present

  - name: apt-get update
    apt:
      update_cache: yes

  - name: Install docker engine
    package:
      name: docker-engine
      state: latest
  when: ansible_os_family == "Debian"
