---
- name: install ag
  homebrew:
    name: the_silver_searcher
    state: latest

- name: install royal-tsx
  shell: brew cask install royal-tsx

- name: install slack
  shell: brew cask install slack
  ignore_errors: yes # preinstalled version causing error

- name: install libressl for teams
  shell: brew install libressl

- name: install teams
  shell: brew cask install microsoft-teams
